spring:
  mail:
    host: 52.98.67.162
    username: dmchan@hotmail.com
    password: 8888
    port: 587
    smtp:
      auth: true
      starttls:
         enable: true
         required: true
    